In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [4]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [7]:
#Label Encoding 
#its a preprocessing step converting the labels into numeric form 
#so as to convert it into the machine-readable form

In [8]:
#one hot encoding 
#It refers to splitting the column which contains numerical categorical data 
#to many columns depending on the number of categories present in that column. 
#Each column contains “0” or “1” corresponding to which column it has been placed.

In [9]:
#remove dummy variables
#The Dummy Variable trap is a scenario in which the independent variables are multicollinear - 
#two or more variables are highly correlated; in simple terms one variable can be predicted from the others.

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [11]:
np.unique(X[:, 1])

array([0, 1, 2], dtype=object)

In [12]:
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(columnTransformer.fit_transform(X), dtype = np.float)

#remove dummy variables 
X = X[:, 1:]

In [13]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
#StandardScaler : It transforms the data in such a manner that it has mean as 0 and standard deviation as 1.
#Standardization is useful for data which has negative values. It arranges the data in normal distribution

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
#Keras is an open source neural network library written in Python. It is capable of running on top of TensorFlow. 
#It is designed to enable fast experimentation with deep neural networks.

In [18]:
#Tensor flow:- math library that is used for machine learning applications like neural networks.

In [19]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [20]:
# Initialising the ANN
#Linear stack of layers.
classifier = Sequential()
#`Dense` implements the operation:
#`output = activation(dot(input, kernel) + bias)`
#where `activation` is the element-wise activation function
#passed as the `activation` argument, `kernel` is a weights matrix
#created by the layer, and `bias` is a bias vector created by the layer
# Adding the input layer and the first hidden layer
#Adds a layer instance on top of the layer stack.
#uniformly distributed weights
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))
#cross entropy log loss
#measures the performance of a classification model whose output is a probability value between 0 and 1. 
#Cross-entropy loss increases as the predicted probability diverges from the actual label.
#accuracy is the fraction of predictions our model got right
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 3s 335us/step - loss: 0.4950 - accuracy: 0.7956
Epoch 2/100
8000/8000 [==============================] - 2s 199us/step - loss: 0.4183 - accuracy: 0.8119
Epoch 3/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.4042 - accuracy: 0.8261
Epoch 4/100
8000/8000 [==============================] - 2s 220us/step - loss: 0.3934 - accuracy: 0.8294
Epoch 5/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.3856 - accuracy: 0.82900s
Epoch 6/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3800 - accuracy: 0.8299
Epoch 7/100
8000/8000 [==============================] - 2s 194us/step - loss: 0.3753 - accuracy: 0.8354
Epoch 8/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.3723 - accuracy: 0.8439
Epoch 9/100
8000/8000 [===============

In [21]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [22]:
cm

array([[1491,  104],
       [ 175,  230]])

In [23]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [27]:
X_train.shape

(8000, 11)

In [30]:
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________
